"""empty message

Revision ID: 0fa48641e77d
Revises: 6d5f9deacc9b
Create Date: 2021-01-28 14:22:59.140815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa48641e77d'
down_revision = '6d5f9deacc9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('films', 'img_url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('films', 'img_url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
