"""empty message

Revision ID: 3b89f9a4d55a
Revises: 0fa48641e77d
Create Date: 2021-03-21 20:56:13.159995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b89f9a4d55a'
down_revision = '0fa48641e77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'meta_score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('meta_score', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
